// Generated by `npm run theme` from packages/react/src/catalog/strings.ts. Do not edit: a test fails if
// this file is stale.

/// The renderer's own words (PLAN-THEMES.md): English unless the app gives its own, with
/// `.omniStrings(…)`. They are shown as plain text, and placeholders such as {value} are filled in one
/// plain pass (`fillTemplate`), so nothing in them is interpreted. Set by the app, never by the stream.
public struct OmniStrings: Sendable, Equatable {
  public var loading: String
  public var failedToLoad: String
  public var failedToRender: String
  public var unsupported: String
  public var rating: String
  public var user: String
  public var assistant: String
  public var value: String
  public var chooseDate: String
  public var ok: String
  public var cancel: String
  public var sections: String
  public var newerVersion: String
  public var blocked: String
  public var required: String
  public var chooseOption: String
  public var turnOn: String
  public var invalidEmail: String
  public var invalidNumber: String
  public var invalidPhone: String
  public var invalidUrl: String
  public var tooShort: String
  public var tooLong: String
  public var dateTooEarly: String
  public var dateTooLate: String
  public var confirm: String

  public init(
    loading: String = "Loading",
    failedToLoad: String = "Component failed to load",
    failedToRender: String = "Component failed to render",
    unsupported: String = "This part of the screen can't be shown here.",
    rating: String = "Rated {value} out of {max}",
    user: String = "You",
    assistant: String = "Assistant",
    value: String = "Value",
    chooseDate: String = "Choose a date",
    ok: String = "OK",
    cancel: String = "Cancel",
    sections: String = "Sections",
    newerVersion: String = "This screen was made for a newer version of the app. The app needs an update to show all of it.",
    blocked: String = "This can't be sent. Check the details and try again.",
    required: String = "This is required.",
    chooseOption: String = "Choose an option.",
    turnOn: String = "Turn this on to continue.",
    invalidEmail: String = "Enter an email address, like name@example.com.",
    invalidNumber: String = "Enter a number.",
    invalidPhone: String = "Enter a phone number.",
    invalidUrl: String = "Enter a web address that starts with https://.",
    tooShort: String = "Use at least {min} characters.",
    tooLong: String = "Use {max} characters or fewer.",
    dateTooEarly: String = "Choose {min} or later.",
    dateTooLate: String = "Choose {max} or earlier.",
    confirm: String = "Confirm"
  ) {
    self.loading = loading
    self.failedToLoad = failedToLoad
    self.failedToRender = failedToRender
    self.unsupported = unsupported
    self.rating = rating
    self.user = user
    self.assistant = assistant
    self.value = value
    self.chooseDate = chooseDate
    self.ok = ok
    self.cancel = cancel
    self.sections = sections
    self.newerVersion = newerVersion
    self.blocked = blocked
    self.required = required
    self.chooseOption = chooseOption
    self.turnOn = turnOn
    self.invalidEmail = invalidEmail
    self.invalidNumber = invalidNumber
    self.invalidPhone = invalidPhone
    self.invalidUrl = invalidUrl
    self.tooShort = tooShort
    self.tooLong = tooLong
    self.dateTooEarly = dateTooEarly
    self.dateTooLate = dateTooLate
    self.confirm = confirm
  }

  public static let english = OmniStrings()
}
