// Generated by `npm run theme` from packages/react/src/catalog/strings.ts. Do not edit: a test fails if
// this file is stale.

/// The renderer's own words (PLAN-THEMES.md): English unless the app gives its own, with
/// `.omniStrings(…)`. They are shown as plain text, and placeholders such as {value} are filled in one
/// plain pass (`fillTemplate`), so nothing in them is interpreted. Set by the app, never by the stream.
public struct OmniStrings: Sendable, Equatable {
  public var loading: String
  public var failedToLoad: String
  public var failedToRender: String
  public var rating: String
  public var user: String
  public var assistant: String
  public var value: String
  public var chooseDate: String
  public var ok: String
  public var cancel: String
  public var sections: String
  public var newerVersion: String
  public var blocked: String

  public init(
    loading: String = "Loading",
    failedToLoad: String = "Component failed to load",
    failedToRender: String = "Component failed to render",
    rating: String = "Rated {value} out of {max}",
    user: String = "You",
    assistant: String = "Assistant",
    value: String = "Value",
    chooseDate: String = "Choose a date",
    ok: String = "OK",
    cancel: String = "Cancel",
    sections: String = "Sections",
    newerVersion: String = "This screen was made for a newer version of the app. The app needs an update to show all of it.",
    blocked: String = "This can't be sent. Check the details and try again."
  ) {
    self.loading = loading
    self.failedToLoad = failedToLoad
    self.failedToRender = failedToRender
    self.rating = rating
    self.user = user
    self.assistant = assistant
    self.value = value
    self.chooseDate = chooseDate
    self.ok = ok
    self.cancel = cancel
    self.sections = sections
    self.newerVersion = newerVersion
    self.blocked = blocked
  }

  public static let english = OmniStrings()
}
