// Generated by `npm run theme` from packages/react/src/catalog/theme.ts (also conformance/theme.json).
// Do not edit: a test fails if this file is stale.

/// The design tokens' default colours (PLAN-THEMES.md), as 0xRRGGBB, for the light and dark themes.
/// The app sets the look, never the stream.
public struct OmniPalette: Sendable, Equatable {
  public var surface: UInt32
  public var text: UInt32
  public var mutedText: UInt32
  public var labelText: UInt32
  public var border: UInt32
  public var inputBorder: UInt32
  public var divider: UInt32
  public var subtle: UInt32
  public var placeholder: UInt32
  public var placeholderHighlight: UInt32
  public var accent: UInt32
  public var onAccent: UInt32
  public var accentSoft: UInt32
  public var success: UInt32
  public var successSoft: UInt32
  public var successText: UInt32
  public var warning: UInt32
  public var warningSoft: UInt32
  public var warningText: UInt32
  public var danger: UInt32
  public var dangerSoft: UInt32
  public var dangerText: UInt32
  public var chartAxis: UInt32
  public var chart1: UInt32
  public var chart2: UInt32
  public var chart3: UInt32
  public var chart4: UInt32
  public var chart5: UInt32
  public var chart6: UInt32
  public var chart7: UInt32
  public var chart8: UInt32

  /// The chart colours, in order.
  public var charts: [UInt32] { [chart1, chart2, chart3, chart4, chart5, chart6, chart7, chart8] }

  public static let light = OmniPalette(
    surface: 0xFFFFFF,
    text: 0x1F2329,
    mutedText: 0x5B616E,
    labelText: 0x3C4048,
    border: 0xD9DCE1,
    inputBorder: 0x868C97,
    divider: 0xE3E5E8,
    subtle: 0xEEF0F3,
    placeholder: 0xECEEF1,
    placeholderHighlight: 0xF6F7F9,
    accent: 0x1F5EFF,
    onAccent: 0xFFFFFF,
    accentSoft: 0xEEF3FF,
    success: 0x2E7D32,
    successSoft: 0xE3F4E6,
    successText: 0x1B5E20,
    warning: 0xB7791F,
    warningSoft: 0xFFF4D6,
    warningText: 0x7A5200,
    danger: 0xC62828,
    dangerSoft: 0xFDE4E4,
    dangerText: 0x8E1C1C,
    chartAxis: 0x9AA0AA,
    chart1: 0x2A78D6,
    chart2: 0xEB6834,
    chart3: 0x1BAF7A,
    chart4: 0xEDA100,
    chart5: 0xE87BA4,
    chart6: 0x008300,
    chart7: 0x4A3AA7,
    chart8: 0xE34948)

  public static let dark = OmniPalette(
    surface: 0x1B2029,
    text: 0xE6E8EC,
    mutedText: 0xA3AAB6,
    labelText: 0xC7CCD4,
    border: 0x343B47,
    inputBorder: 0x737B89,
    divider: 0x2C333E,
    subtle: 0x262C36,
    placeholder: 0x2A303A,
    placeholderHighlight: 0x353C47,
    accent: 0x7C9DFF,
    onAccent: 0x0D1428,
    accentSoft: 0x1D2846,
    success: 0x6FCF86,
    successSoft: 0x18301F,
    successText: 0x9FE0AE,
    warning: 0xE5A93F,
    warningSoft: 0x34290F,
    warningText: 0xF2C770,
    danger: 0xFF7B72,
    dangerSoft: 0x3B1A1A,
    dangerText: 0xFFA59E,
    chartAxis: 0x6B7381,
    chart1: 0x5B9CF0,
    chart2: 0xF38A5E,
    chart3: 0x3CC995,
    chart4: 0xF0B429,
    chart5: 0xF09BBD,
    chart6: 0x3FAE3F,
    chart7: 0x9B8CF0,
    chart8: 0xF07676)
}
