// The differential corpus (PLAN-HARDENING.md, B.2): a fixed set of generated, mostly broken streams
// with the TypeScript parser's results, in the conformance case format. The Swift and Kotlin test
// suites run every case and must reach exactly the same result.
//
// This is not a conformance suite: conformance cases are written from the spec, while these
// results only record what the TypeScript parser does. Any disagreement is settled by SPEC.md,
// and the case becomes a conformance case.
//
// fuzz/live-corpus.json does the same for updates (SPEC.md [10.29]-[10.34]): fixtures with random
// updates, each update's result and the screen after the last.
//
//   npm run fuzz:corpus             write fuzz/corpus.json and fuzz/live-corpus.json
//   npm run fuzz:corpus -- --check  fail if it is out of date
import { readFileSync, writeFileSync } from "node:fs";
import fc from "fast-check";
import { parseCanonical, parseWithUpdates } from "../tests/canonical";
import { fixtureTexts, FUZZ_ASSETS, FUZZ_COMPONENTS, FUZZ_PICTURES, FUZZ_TOOLS, mutatedFixture, screenWithUpdates, stream } from "./arbitraries";

export const CORPUS_FILE = "fuzz/corpus.json";
export const LIVE_CORPUS_FILE = "fuzz/live-corpus.json";
const LIVE_SIZE = 300;
const SEED = 20261005;
const SIZE = { stream: 1200, fixture: 800 };

/** Valid Unicode only (lone surrogates become U+FFFD), so every language reads the same text. */
const portable = (s: string) => s.replace(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/g, "�");

export function buildCorpus(): string {
  const streams = fc.sample(stream, { seed: SEED, numRuns: SIZE.stream });
  const edited = fc.sample(mutatedFixture(fixtureTexts()), { seed: SEED + 1, numRuns: SIZE.fixture });
  const cases = [...streams, ...edited].map((raw, i) => {
    const input = portable(raw);
    return {
      id: `fuzz-${String(i + 1).padStart(4, "0")}`,
      rules: [],
      description: i < SIZE.stream ? "generated stream" : "edited fixture",
      input,
      tools: [...FUZZ_TOOLS],
      assets: [...FUZZ_ASSETS],
      components: FUZZ_COMPONENTS,
      pictures: FUZZ_PICTURES,
      expect: parseCanonical([input], { tools: FUZZ_TOOLS, assets: FUZZ_ASSETS, components: FUZZ_COMPONENTS, pictures: FUZZ_PICTURES }),
    };
  });
  const file = {
    $comment:
      "Generated by fuzz/build.ts (npm run fuzz:corpus). Results are the TypeScript parser's, not the spec's: other parsers must agree with them, and a disagreement is settled by SPEC.md.",
    seed: SEED,
    cases,
  };
  return `${JSON.stringify(file, null, 1)}\n`;
}

/** Fixtures with random updates, in the conformance case format with `updates` (conformance/README.md). */
export function buildLiveCorpus(): string {
  const registry = { tools: FUZZ_TOOLS, assets: FUZZ_ASSETS, components: FUZZ_COMPONENTS, pictures: FUZZ_PICTURES };
  const cases = fc.sample(screenWithUpdates(fixtureTexts()), { seed: SEED + 2, numRuns: LIVE_SIZE }).map(({ screen, updates }, i) => {
    const input = portable(screen);
    const texts = updates.map(portable);
    const result = parseWithUpdates([input], texts, registry);
    return {
      id: `live-fuzz-${String(i + 1).padStart(3, "0")}`,
      rules: [],
      description: "fixture with generated updates",
      input,
      tools: [...FUZZ_TOOLS],
      assets: [...FUZZ_ASSETS],
      components: FUZZ_COMPONENTS,
      pictures: FUZZ_PICTURES,
      expect: result.screen,
      updates: texts.map((text, n) => ({ input: text, expect: result.updates[n]! })),
    };
  });
  const file = {
    $comment:
      "Generated by fuzz/build.ts (npm run fuzz:corpus). Results are the TypeScript parser's, not the spec's: other parsers must agree with them, and a disagreement is settled by SPEC.md.",
    seed: SEED + 2,
    cases,
  };
  return `${JSON.stringify(file, null, 1)}\n`;
}

if (process.argv[1]?.replace(/\\/g, "/").endsWith("fuzz/build.ts")) {
  for (const [file, text] of [[CORPUS_FILE, buildCorpus()], [LIVE_CORPUS_FILE, buildLiveCorpus()]] as const) {
    if (process.argv.includes("--check")) {
      if (readFileSync(file, "utf8") !== text) {
        console.error(`${file} is out of date: run npm run fuzz:corpus`);
        process.exit(1);
      }
      console.log(`${file} is up to date`);
    } else {
      writeFileSync(file, text);
      console.log(`wrote ${file}: ${Math.round(text.length / 1024)} KB`);
    }
  }
}
