// The differential corpus (PLAN-HARDENING.md, B.2): a fixed set of generated, mostly broken streams
// with the TypeScript parser's results, in the conformance case format. The Swift and Kotlin test
// suites run every case and must reach exactly the same result.
//
// This is not a conformance suite: conformance cases are written from the spec, while these
// results only record what the TypeScript parser does. Any disagreement is settled by SPEC.md,
// and the case becomes a conformance case.
//
//   npm run fuzz:corpus             write fuzz/corpus.json
//   npm run fuzz:corpus -- --check  fail if it is out of date
import { readFileSync, writeFileSync } from "node:fs";
import fc from "fast-check";
import { parseCanonical } from "../tests/canonical";
import { fixtureTexts, FUZZ_ASSETS, FUZZ_COMPONENTS, FUZZ_PICTURES, FUZZ_TOOLS, mutatedFixture, stream } from "./arbitraries";

export const CORPUS_FILE = "fuzz/corpus.json";
const SEED = 20261005;
const SIZE = { stream: 1200, fixture: 800 };

/** Valid Unicode only (lone surrogates become U+FFFD), so every language reads the same text. */
const portable = (s: string) => s.replace(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/g, "�");

export function buildCorpus(): string {
  const streams = fc.sample(stream, { seed: SEED, numRuns: SIZE.stream });
  const edited = fc.sample(mutatedFixture(fixtureTexts()), { seed: SEED + 1, numRuns: SIZE.fixture });
  const cases = [...streams, ...edited].map((raw, i) => {
    const input = portable(raw);
    return {
      id: `fuzz-${String(i + 1).padStart(4, "0")}`,
      rules: [],
      description: i < SIZE.stream ? "generated stream" : "edited fixture",
      input,
      tools: [...FUZZ_TOOLS],
      assets: [...FUZZ_ASSETS],
      components: FUZZ_COMPONENTS,
      pictures: FUZZ_PICTURES,
      expect: parseCanonical([input], { tools: FUZZ_TOOLS, assets: FUZZ_ASSETS, components: FUZZ_COMPONENTS, pictures: FUZZ_PICTURES }),
    };
  });
  const file = {
    $comment:
      "Generated by fuzz/build.ts (npm run fuzz:corpus). Results are the TypeScript parser's, not the spec's: other parsers must agree with them, and a disagreement is settled by SPEC.md.",
    seed: SEED,
    cases,
  };
  return `${JSON.stringify(file, null, 1)}\n`;
}

if (process.argv[1]?.replace(/\\/g, "/").endsWith("fuzz/build.ts")) {
  const text = buildCorpus();
  if (process.argv.includes("--check")) {
    const current = readFileSync(CORPUS_FILE, "utf8");
    if (current !== text) {
      console.error(`${CORPUS_FILE} is out of date: run npm run fuzz:corpus`);
      process.exit(1);
    }
    console.log(`${CORPUS_FILE} is up to date`);
  } else {
    writeFileSync(CORPUS_FILE, text);
    console.log(`wrote ${CORPUS_FILE}: ${SIZE.stream + SIZE.fixture} cases, ${Math.round(text.length / 1024)} KB`);
  }
}
