// Generated by `npm run theme` from packages/react/src/catalog/strings.ts. Do not edit: a test fails if
// this file is stale.
package dev.omniir.runtime

/**
 * The renderer's own words (PLAN-THEMES.md): English unless the app gives its own, for example
 * `OmniStrings(loading = "Chargement")`. They are shown as plain text, and placeholders such as {value}
 * are filled in one plain pass ([fillTemplate]), so nothing in them is interpreted. Set by the app,
 * never by the stream.
 */
public data class OmniStrings(
  public val loading: String = "Loading",
  public val failedToLoad: String = "Component failed to load",
  public val failedToRender: String = "Component failed to render",
  public val rating: String = "Rated {value} out of {max}",
  public val user: String = "You",
  public val assistant: String = "Assistant",
  public val value: String = "Value",
  public val chooseDate: String = "Choose a date",
  public val ok: String = "OK",
  public val cancel: String = "Cancel",
  public val sections: String = "Sections",
  public val newerVersion: String = "This screen was made for a newer version of the app. The app needs an update to show all of it.",
  public val blocked: String = "This can't be sent. Check the details and try again.",
)
