// The design tokens (packages/react/src/catalog/theme.ts) written where they are used:
// - the token block at the top of packages/react/src/catalog/omni.css (light, dark, and dark on a
//   dark device when the app chose "system");
// - conformance/theme.json, the language-neutral list for other renderers;
// - the same defaults for the Swift and Kotlin catalogs (OmniPalette), so the three can't drift.
// Run: npm run theme (or -- --check). Tests fail if either is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { ENGLISH } from "../packages/react/src/catalog/strings";
import { COLOR_TOKENS, CONTRAST_PAIRS, DARK, LIGHT, SHAPE, cssVariable, type Palette } from "../packages/react/src/catalog/theme";

const CSS_FILE = "packages/react/src/catalog/omni.css";
const JSON_FILE = "conformance/theme.json";
export const SWIFT_THEME_PATH = "swift/Sources/OmniIRSwiftUI/Model/Theme.generated.swift";
export const KOTLIN_THEME_PATH = "android/omni-ir-runtime/src/main/kotlin/dev/omniir/runtime/Theme.generated.kt";
export const SWIFT_STRINGS_PATH = "swift/Sources/OmniIRSwiftUI/Model/Strings.generated.swift";
export const KOTLIN_STRINGS_PATH = "android/omni-ir-runtime/src/main/kotlin/dev/omniir/runtime/Strings.generated.kt";

/** A Swift or Kotlin string literal: the English table is plain ASCII, so only \ " and $ need escaping. */
function literal(text: string): string {
  if (!/^[\x20-\x7e]*$/.test(text)) throw new Error(`not plain ASCII: ${text}`);
  return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;
}
const hex = (color: string) => color.slice(1).toUpperCase();
const BLOCK = /\/\* generated:theme \*\/[\s\S]*?\/\* \/generated:theme \*\//;

const declarations = (palette: Palette, indent: string) => COLOR_TOKENS.map((t) => `${indent}${cssVariable(t)}: ${palette[t]};`).join("\n");

/** The token block of omni.css. :where() keeps it at zero specificity, so an app's `.omni-root { --omni-accent: … }` always wins. */
export function themeCss(): string {
  return `/* generated:theme */
:where(.omni-root) {
${declarations(LIGHT, "  ")}
  ${cssVariable("font")}: ${SHAPE.font};
  ${cssVariable("radius")}: ${SHAPE.radius};
  color: var(--omni-text);
  font-family: var(--omni-font);
}
:where(.omni-root[data-theme="dark"]) {
${declarations(DARK, "  ")}
  color-scheme: dark;
}
@media (prefers-color-scheme: dark) {
  :where(.omni-root[data-theme="system"]) {
${declarations(DARK, "    ")}
    color-scheme: dark;
  }
}
/* /generated:theme */`;
}

export function themeJson(): string {
  return (
    JSON.stringify(
      {
        description: "Omni-IR design tokens: the colours, font and corner radius a renderer draws with, set by the app, never by the stream. Colours are #rrggbb.",
        tokens: [...COLOR_TOKENS],
        light: LIGHT,
        dark: DARK,
        shape: { radius: Number.parseFloat(SHAPE.radius), radiusUnit: "px" },
        contrast: CONTRAST_PAIRS.map(([foreground, background, minimum, what]) => ({ foreground, background, minimum, what })),
      },
      null,
      2,
    ) + "\n"
  );
}

/** OmniPalette for Swift: the default colours as 0xRRGGBB. */
export function themeSwift(): string {
  const fields = COLOR_TOKENS.map((t) => `  public var ${t}: UInt32`).join("\n");
  const init = (palette: Palette) => `OmniPalette(\n${COLOR_TOKENS.map((t) => `    ${t}: 0x${hex(palette[t])}`).join(",\n")})`;
  return `// Generated by \`npm run theme\` from packages/react/src/catalog/theme.ts (also conformance/theme.json).
// Do not edit: a test fails if this file is stale.

/// The design tokens' default colours (PLAN-THEMES.md), as 0xRRGGBB, for the light and dark themes.
/// The app sets the look, never the stream.
public struct OmniPalette: Sendable, Equatable {
${fields}

  /// The chart colours, in order.
  public var charts: [UInt32] { [${[1, 2, 3, 4, 5, 6, 7, 8].map((n) => `chart${n}`).join(", ")}] }

  public static let light = ${init(LIGHT)}

  public static let dark = ${init(DARK)}
}
`;
}

/** OmniPalette for Kotlin: the default colours as ARGB longs (0xFFRRGGBB), ready for Compose's Color(Long). */
export function themeKotlin(): string {
  const fields = COLOR_TOKENS.map((t) => `  public val ${t}: Long,`).join("\n");
  const init = (palette: Palette) => `OmniPalette(\n${COLOR_TOKENS.map((t) => `      ${t} = 0xFF${hex(palette[t])},`).join("\n")}\n    )`;
  return `// Generated by \`npm run theme\` from packages/react/src/catalog/theme.ts (also conformance/theme.json).
// Do not edit: a test fails if this file is stale.
package dev.omniir.runtime

/**
 * The design tokens' default colours (PLAN-THEMES.md), as ARGB longs for the light and dark themes.
 * The app sets the look, never the stream.
 */
public data class OmniPalette(
${fields}
) {
  /** The chart colours, in order. */
  public val charts: List<Long> get() = listOf(${[1, 2, 3, 4, 5, 6, 7, 8].map((n) => `chart${n}`).join(", ")})

  public companion object {
    public val LIGHT: OmniPalette = ${init(LIGHT)}

    public val DARK: OmniPalette = ${init(DARK)}
  }
}
`;
}

/** OmniStrings for Swift: the renderer's own words, English by default, each replaceable by the app. */
export function stringsSwift(): string {
  const keys = Object.keys(ENGLISH) as (keyof typeof ENGLISH)[];
  return `// Generated by \`npm run theme\` from packages/react/src/catalog/strings.ts. Do not edit: a test fails if
// this file is stale.

/// The renderer's own words (PLAN-THEMES.md): English unless the app gives its own, with
/// \`.omniStrings(…)\`. They are shown as plain text, and placeholders such as {value} are filled in one
/// plain pass (\`fillTemplate\`), so nothing in them is interpreted. Set by the app, never by the stream.
public struct OmniStrings: Sendable, Equatable {
${keys.map((k) => `  public var ${k}: String`).join("\n")}

  public init(
${keys.map((k) => `    ${k}: String = ${literal(ENGLISH[k])}`).join(",\n")}
  ) {
${keys.map((k) => `    self.${k} = ${k}`).join("\n")}
  }

  public static let english = OmniStrings()
}
`;
}

/** OmniStrings for Kotlin: the renderer's own words, English by default, each replaceable by the app. */
export function stringsKotlin(): string {
  const keys = Object.keys(ENGLISH) as (keyof typeof ENGLISH)[];
  return `// Generated by \`npm run theme\` from packages/react/src/catalog/strings.ts. Do not edit: a test fails if
// this file is stale.
package dev.omniir.runtime

/**
 * The renderer's own words (PLAN-THEMES.md): English unless the app gives its own, for example
 * \`OmniStrings(loading = "Chargement")\`. They are shown as plain text, and placeholders such as {value}
 * are filled in one plain pass ([fillTemplate]), so nothing in them is interpreted. Set by the app,
 * never by the stream.
 */
public data class OmniStrings(
${keys.map((k) => `  public val ${k}: String = ${literal(ENGLISH[k])},`).join("\n")}
)
`;
}

const OUTPUTS: [string, () => string][] = [
  [JSON_FILE, themeJson],
  [SWIFT_THEME_PATH, themeSwift],
  [KOTLIN_THEME_PATH, themeKotlin],
  [SWIFT_STRINGS_PATH, stringsSwift],
  [KOTLIN_STRINGS_PATH, stringsKotlin],
];
const read = (path: string) => {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return "";
  }
};

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const check = process.argv.includes("--check");
  const css = readFileSync(CSS_FILE, "utf8");
  const nextCss = css.replace(BLOCK, themeCss());
  const stale = [css !== nextCss && CSS_FILE, ...OUTPUTS.map(([path, render]) => read(path) !== render() && path)].filter(Boolean);
  if (check) {
    if (stale.length) {
      console.error(`stale: ${stale.join(", ")} (run npm run theme)`);
      process.exit(1);
    }
    console.log("theme up to date");
  } else {
    writeFileSync(CSS_FILE, nextCss);
    for (const [path, render] of OUTPUTS) writeFileSync(path, render());
    console.log(`wrote ${CSS_FILE} (token block), ${OUTPUTS.map(([path]) => path).join(", ")}`);
  }
}
