// The renderer's own words (PLAN-THEMES.md D): the few things it says itself, as opposed to the text a
// stream writes. English is built in; an app passes its own words to OmniRenderer's `strings`. The
// same keys exist in the Swift and Kotlin catalogs (generated by `npm run theme`).
//
// They come only from the app's code, never from the stream, and are never sent to a model or server.
// They are shown as plain text, and placeholders such as {value} are filled in one plain pass, so
// nothing in a string (markup, `%d`, a value containing "{max}") is ever interpreted.

export const ENGLISH = {
  /** Read by screen readers while a part of the screen is still arriving. */
  loading: "Loading",
  /** In place of a part of the screen that never arrived. */
  failedToLoad: "Component failed to load",
  /** In place of a part of the screen that failed to draw. */
  failedToRender: "Component failed to render",
  /** A Rating, for screen readers. {value} and {max} are numbers. */
  rating: "Rated {value} out of {max}",
  /** Who sent a Message, for screen readers. */
  user: "You",
  assistant: "Assistant",
  /** The heading of a chart's values in its data table. */
  value: "Value",
  /** A DateInput's button on iOS and Android. */
  chooseDate: "Choose a date",
  /** Confirms and closes the date picker on Android. */
  ok: "OK",
  /** Closes the date picker on Android. */
  cancel: "Cancel",
  /** Names the row of tabs for screen readers on iOS. */
  sections: "Sections",
  /** Shown when a stream needs a newer version of Omni-IR than the app's (SPEC.md [3.9]). */
  newerVersion: "This screen was made for a newer version of the app. The app needs an update to show all of it.",
  /** Under a button whose action couldn't be sent; the details go to the app's onEvent. */
  blocked: "This can't be sent. Check the details and try again.",
  // Under a form field that doesn't pass its checks (SPEC.md [8.2]–[8.4]).
  /** An Input or DateInput declared `required` that is empty. */
  required: "This is required.",
  /** A Select declared `required` with nothing chosen. */
  chooseOption: "Choose an option.",
  /** A Switch declared `required` that is off. */
  turnOn: "Turn this on to continue.",
  invalidEmail: "Enter an email address, like name@example.com.",
  invalidNumber: "Enter a number.",
  invalidPhone: "Enter a phone number.",
  invalidUrl: "Enter a web address that starts with https://.",
  /** {min} is a number of characters. */
  tooShort: "Use at least {min} characters.",
  /** {max} is a number of characters. */
  tooLong: "Use {max} characters or fewer.",
  /** {min} is a date, written YYYY-MM-DD. */
  dateTooEarly: "Choose {min} or later.",
  /** {max} is a date, written YYYY-MM-DD. */
  dateTooLate: "Choose {max} or earlier.",
  /** The button that runs an action after the app's confirmation sentence (SPEC.md [9.1]). */
  confirm: "Confirm",
} as const;

export type StringKey = keyof typeof ENGLISH;
export type OmniStrings = { readonly [K in StringKey]: string };

/** The app's words for the keys it gave as text, English for every other key. Unknown keys are ignored. */
export function resolveStrings(custom: Partial<Record<StringKey, string>> | undefined): OmniStrings {
  if (!custom) return ENGLISH;
  const resolved: Record<string, string> = { ...ENGLISH };
  for (const key of Object.keys(ENGLISH) as StringKey[]) {
    const value = Object.hasOwn(custom, key) ? custom[key] : undefined;
    if (typeof value === "string") resolved[key] = value;
  }
  return resolved as OmniStrings;
}

/**
 * Fill `{name}` placeholders in one pass: what is inserted is never scanned again, and anything else,
 * including unknown placeholders and `%` codes, is kept as written.
 */
export function fillTemplate(template: string, values: Readonly<Record<string, string | number>>): string {
  return template.replace(/\{([A-Za-z]+)\}/g, (whole, name: string) => (Object.hasOwn(values, name) ? String(values[name]) : whole));
}
